matrix:

  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      cache: yarn
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder


    - os: linux
      sudo: required
      language: node_js
      node_js: "10"
      cache: yarn
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-multilib
            - g++-8
            - g++-multilib
            - icnsutils
            - graphicsmagick
            - xz-utils
            - xorriso
            - rpm

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        /bin/bash -c "apt-get update && apt-get install -y fakeroot && yarn --link-duplicates --pure-lockfile && yarn make && yarn release"
    else
      yarn make && yarn release 
    fi

install:
  - yarn

branches:
  only:
    - "master"
