image: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: "10"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

branches:
  only:
  - master

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
- yarn make
- yarn release

test: off
