image: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: "10"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - C:\strawberry

init:
  - git config --global core.autocrlf input

branches:
  only:
  - master

install:
  - ps: Install-Product node 8 x64
  - yarn
  - if not exist "C:\strawberry" choco install --yes strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%

build_script:
- .\backend\localSetup.bat
- yarn make
- yarn release

test: off
